server:
  port: 8081

spring:
  application:
    name: JavaSpringStore
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

app:
  jwt:
    secret: someSecretKey
    tokenExpiration: 10m
    refreshTokenExpiration: 30m
    mainSender: "main_sender"

feign:
  url: http://localhost:8082