version: '3'
services:
  postgres:
    image: postgres:12.3
    container_name: authentication
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"